service: topcoder-scheduler-executor-new
useDotenv: true

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 256
  timeout: 60
  lambdaHashingVersion: 20210402
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: '*'
    - Effect: 'Allow'
      Action:
        - states:StartExecution
      Resource: '*'

plugins:
  - serverless-step-functions
  - serverless-bundle

custom:
  bundle:
    linting: false
  dotenv:
    file: true

functions:
  processLambda:
    handler: src/process-lambda.handler
    environment:
      AUTH0_URL: ${env:AUTH0_URL}
      AUTH0_AUDIENCE: ${env:AUTH0_AUDIENCE}
      TOKEN_CACHE_TIME: ${env:TOKEN_CACHE_TIME}
      AUTH0_CLIENT_ID: ${env:AUTH0_CLIENT_ID}
      AUTH0_CLIENT_SECRET: ${env:AUTH0_CLIENT_SECRET}
    
stepFunctions:
  stateMachines:
    scheduler:
      name: StateMachine
      definition:
        StartAt: waitX
        States:
          waitX:
            Type: Wait
            TimestampPath: "$.scheduleTime"
            Next: processTask
          processTask:
            Type: Task
            Resource:
              Fn::GetAtt: [processLambda, Arn]
            End: true
      retain: true
  validate: true 
